print("Arithmetic Operators")
print("\nThey are used to perform mathematical operations")
print("\nAddition\nx + y")
print("\nSubtraction\nx - y")
print("\nMultiplication\nx * y")
print("\nDivision\nx / y")
print("\nModulus\nx % y")
print("\nExponentation\nx ** y")
print("\nFloor Division\nx // y")
print("\nx = 15\ny = 4\n")
x = 15
y = 4
print(f"Addition: ", x + y)
print("Subtraction: ",x - y)
print("Multiplication: ",x * y)
print("Division: ",x / y)
print("Modulus: ",x % y)
print("Exponentation: ",x ** y)
print("Floor Division: ",x // y)
